"""
This file is a cache of rules from modules/ruleList.
And it's automatically generalted by GitHub Action
"""

cache="""  - DOMAIN,room.geniucker.top,✔ ZJU
  - DOMAIN,grade.geniucker.top,✔ ZJU
  - DOMAIN,blackqh.geniucker.top,✔ ZJU
  - DOMAIN,ece220git.geniucker.top,✔ ZJU
  - DOMAIN,gitea.geniucker.top,✔ ZJU
  - DOMAIN-SUFFIX,blackmagicdesign.com,🎯 全球直连
  - DOMAIN-SUFFIX,supercell.com,🎯 全球直连
  - DOMAIN-SUFFIX,clashroyale.com,🎯 全球直连
  - DOMAIN-SUFFIX,clashroyaleapp.com,🎯 全球直连
  - DOMAIN-KEYWORD,rvpn,🎯 全球直连
  - DOMAIN,searxng.geniucker.top,🎯 全球直连
  - DOMAIN,nps.geniucker.top,🎯 全球直连
  - DOMAIN,az.geniucker.top,🎯 全球直连
  - DOMAIN,yacd.geniucker.top,🎯 全球直连
  - DOMAIN-SUFFIX,deepl.com,🎯 全球直连
  - DST-PORT,22,🎯 全球直连
  - 404: Not Found,🛸 PT站
  - DOMAIN-SUFFIX,canvas-user-content.com,✔ ZJU-INTL
  - DOMAIN-KEYWORD,illinois,✔ ZJU-INTL
  - DOMAIN-KEYWORD,uiuc,✔ ZJU-INTL
  - DOMAIN-KEYWORD,sso,✔ ZJU-INTL
  - DOMAIN-KEYWORD,shibboleth,✔ ZJU-INTL
  - DOMAIN-SUFFIX,duosecurity.com,✔ ZJU-INTL
  - DOMAIN-SUFFIX,insops.net,✔ ZJU-INTL
  - DOMAIN-SUFFIX,zoom.us,✔ ZJU-INTL
  - 404: Not Found,✔ ZJU
  - 404: Not Found,📃 ZJU More Scholar
  - DOMAIN,chat.zhile.io,🤖 ChatBot
  - 404: Not Found,🤖 ChatBot
  - 404: Not Found,🤖 ChatBot
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🛑 广告拦截
  - 404: Not Found,🍃 应用净化
  - 404: Not Found,🛑 广告拦截
  - 404: Not Found,🛑 广告拦截
  - 404: Not Found,🛡️ 隐私防护
  - 404: Not Found,📢 谷歌FCM
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,Ⓜ️ 微软云盘
  - 404: Not Found,Ⓜ️ 微软服务
  - 404: Not Found,🍎 苹果服务
  - 404: Not Found,📲 电报消息
  - 404: Not Found,🎶 网易音乐
  - 404: Not Found,🎶 Spotify
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,🎮 游戏平台
  - 404: Not Found,📹 油管视频
  - 404: Not Found,🎥 奈飞视频
  - 404: Not Found,📺 巴哈姆特
  - 404: Not Found,📺 哔哩哔哩
  - 404: Not Found,📺 哔哩哔哩
  - 404: Not Found,🌏 国内媒体
  - 404: Not Found,🌍 国外媒体
  - 404: Not Found,🚀 节点选择
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - 404: Not Found,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼"""